const BookCategories = {
  FICTION: "Fiction",
  MYSTERY: "Mystery",
  THRILLER: "Thriller",
  CRIME: "Crime",
  ROMANCE: "Romance",
  FANTASY: "Fantasy",
  SCIENCE_FICTION: "Science Fiction",
  HORROR: "Horror",
  HISTORICAL_FICTION: "Historical Fiction",
  ADVENTURE: "Adventure",
  DYSTOPIAN: "Dystopian",
  YOUNG_ADULT: "Young Adult",
  CHILDRENS_BOOKS: "Children's Books",
  GRAPHIC_NOVELS: "Graphic Novels",
  COMICS: "Comics",
  POETRY: "Poetry",
  NON_FICTION: "Non-Fiction",
  MANGA: "Manga",
  BIOGRAPHY: "Biography",
  AUTObIOGRAPHY: "Autobiography",
  MEMOIR: "Memoir",
  PERSONAL_DEVELOPMENT: "Personal Development",
  PSYCHOLOGY: "Psychology",
  SCIENCE_NATURE: "Science/Nature",
  HISTORY: "History",
  POLITICS_GOVERNMENT: "Politics/Government",
  PHILOSOPHY: "Philosophy",
  RELIGION_SPIRITUALITY: "Religion/Spirituality",
  TRAVEL: "Travel",
  COOKING_FOOD: "Cookbooks/Food",
  HEALTH_FITNESS: "Health/Fitness",
  ART_PHOTOGRAPHY: "Art/Photography",
  MUSIC: "Music",
  BUSINESS_ENTREPRENEURSHIP: "Business/Entrepreneurship",
  ECONOMICS: "Economics",
  TECHNOLOGY_COMPUTER_SCIENCE: "Technology/Computer Science",
  PARENTING_FAMILY: "Parenting/Family",
  RELATIONSHIPS: "Relationships",
  SPORTS: "Sports",
  TRUE_CRIME: "True Crime",
  ESSAYS: "Essays",
  ANTHOLOGIES: "Anthologies",
  REFERENCE_GUIDES: "Reference/Guides",
  EDUCATION: "Education",
  ENVIRONMENTAL_CLIMATE: "Environmental/Climate",
  CULTURAL_SOCIAL_ISSUES: "Cultural/Social Issues",
  LITERARY_CRITICISM: "Critiques on Literature",
  SHORT_STORY_COLLECTIONS: "Short Story Collections",
  CLASSIC_LITERATURE: "Classic Literature",
  JUVENILE_FICTION: "Juvienile Fiction",
  ANTIQUES_COLLECTIBLES: "Antiques Collectibles",
  LITERARY_COLLECTIONS: "Literary Collections",
  ARCHITECTURE: "Architecture",
  MATHEMATICS: "Mathematics",
  BIBLES: "Bibles",
  MEDICAL: "Medical",
  BODY_MIND_SPIRIT: "Body Mind Spirit",
  PERFORMING_ARTS: "Performing Arts",
  PETS: "Pets",
  COMPUTERS: "Computers",
  CRAFTS_HOBBIES: "Crafts Hobbies",
  DESIGN: "Design",
  POLITICAL_SCIENCE: "Political Science",
  DRAMA: "Drama",
  FOREIGN_LANGUAGE_STUDY: "Foreign Language Study",
  SELF_HELP: "Self Help",
  GAMES_ACTIVITIES: "Games Activities",
  GARDENING: "Gardening",
  STUDY_AIDS: "Study Aids",
  HOUSE_HOME: "House Home",
  TRANSPORTATION: "Transportation",
  HUMOR: "Humor",
  JUVENILE_NONFICTION: "Juvenile Nonfiction",
  YOUNG_ADULT_FICTION: "Young Adult Fiction",
  LANGUAGE_ARTS_DISCIPLINES: "Language Arts Disciplines",
  YOUNG_ADULT_NONFICTION: "Young Adult Nonfiction",
  LAW: "Law",
};

export default BookCategories;
